### ISSUE TITLE
Pydantic 2.0 Update

### ISSUE THREAD

**Issue by daquinteroflex** [flexcompute/Flow360#248]
Hello! Just thought to raise this issue to track it - I'll see if I can find a way around this for now. 

Unfortunately, in a given venv, it is not possible to install `tidy3d` and `flow360` since tidy3d uses pydantic 2.0 and flow360 uses pydantic 1.0.  This raises some fundamental issues when trying to use poetry to manage the toolchains together, or even pip install the two packages in the same environment. I might give more details about the issues in the backend repos correspondingly of down the line issues.

This is a big change, and a nontrivial amount of work, but thought just to raise to have in mind. Maybe it's important depending on closer integration between the projects beyond standard bash scripts into actual interconnected python methods.

**Comment by benflexcompute** [comment]
Hi @daquinteroflex we have upgraded pydantic as dependency to latest V2.7.
See this PR: https://github.com/flexcompute/Flow360/pull/247/files#:~:text=.0%22-,pydantic%20%3D%20%22%5E2.7.0%22,-pytest%20%3D%20%22
Most things still use pydantic V1 as:
import pydantic.v1 as pd.

**Comment by daquinteroflex** [comment]
Oh that's great, I the version I had was not upgraded yet so this is perfect. Thanks a lot
